#!/bin/bash
user=$(whoami)

SITE_PATH="/Users/${user}/Sites/new-site/img/project"

cd $SITE_PATH
echo $SITE_PATH

 for folder in */; do
 	cd $folder;
 	if [ !  -d "thumbs" ]; then
 		echo "Generating thumbnails for $folder"
 		mkdir thumbs;
 		for f in *.jpg; do
 			#convert $f -resize 150 -set filename:f "%t_t" thumbs/%[filename:f].jpg;
			 convert $f -resize x300 -set filename:f "%t_t" thumbs/%[filename:f].jpg; 
			# convert $f -resize x620 -set filename:f "%t_z" thumbs/%[filename:f].jpg; 
		done
	fi
	rm -f *.*\~
	cd ~-;
done

echo "Thumb snails created"